# fly.toml app configuration file generated for calorie-counter on 2024-02-05T06:57:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "calorie-counter"
primary_region = "iad"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
